# Generated by Django 3.2.6 on 2021-12-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('site', models.URLField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
