# Generated by Django 3.2.6 on 2021-12-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('number', models.IntegerField()),
                ('place', models.CharField(choices=[('Kottayam', 'Kottayam'), ('Alappuzha', 'Alappuzha'), ('kollam', 'Kollam'), ('ekm', 'ekm'), ('trivandram', 'trivandram')], max_length=25)),
                ('job', models.CharField(max_length=100)),
                ('vaccines', models.CharField(max_length=100)),
                ('traveling', models.CharField(max_length=100)),
                ('covidecheck', models.CharField(max_length=100)),
            ],
        ),
    ]
