# Generated by Django 3.2.6 on 2021-12-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='age',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='forms',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
