# Generated by Django 3.2.6 on 2021-12-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0002_auto_20211210_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='forms',
            name='number',
            field=models.IntegerField(),
        ),
    ]
