# Generated by Django 3.2.6 on 2021-12-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0003_auto_20211210_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
