# Generated by Django 3.2.6 on 2021-12-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0004_alter_forms_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='place',
            field=models.CharField(max_length=25),
        ),
    ]
