# Generated by Django 3.2.6 on 2021-12-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0005_alter_forms_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='number',
            field=models.IntegerField(max_length=5),
        ),
    ]
