# Generated by Django 3.2.6 on 2021-12-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0006_alter_forms_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='forms',
            name='number',
            field=models.IntegerField(),
        ),
    ]
